name: Tagging Build

on:
  push:
    tags:
      - '*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Build with dotnet
      run: |
        REF=${{ github.ref }}
        TAG=${REF/refs\/tags\//}
        ARGS="-p:Version=$TAG -p:PackageVersion=$TAG"
        # Allow to override Nuget Package Id for testing folk repositories
        PACKAGE_ID=${{ secrets.PACKAGE_ID }}
        [ ! -z "$PACKAGE_ID" ] && ARGS="$ARGS -p:PackageId=$PACKAGE_ID"
        dotnet pack DotNet.Jdt.sln --configuration Release $ARGS --output dist

    - name: Push Nuget Package
      run: |
        dotnet nuget push dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
